In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# sample_sub = pd.read_csv('../data/sample_submission.csv')
store = pd.read_csv('../data/store.csv')
train = pd.read_csv('../data/train.csv')
test = pd.read_csv('../data/test.csv')

/home/owon/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3398: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [3]:
def unique_vals(df):
  for col in df.columns:
    print(col)
    print(df[col].unique()[:10])
    print("__________________\n******************\n")

# Datasets

### Store Information Dataset

In [4]:
store.head(5)

Store StoreType Assortment  CompetitionDistance  CompetitionOpenSinceMonth  \
0      1         c          a               1270.0                        9.0   
1      2         a          a                570.0                       11.0   
2      3         a          a              14130.0                       12.0   
3      4         c          c                620.0                        9.0   
4      5         a          a              29910.0                        4.0   

   CompetitionOpenSinceYear  Promo2  Promo2SinceWeek  Promo2SinceYear  \
0                    2008.0       0              NaN              NaN   
1                    2007.0       1             13.0           2010.0   
2                    2006.0       1             14.0           2011.0   
3                    2009.0       0              NaN              NaN   
4                    2015.0       0              NaN              NaN   

     PromoInterval  
0              NaN  
1  Jan,Apr,Jul,Oct  
2  Jan,Apr,Jul,Oct  
3              NaN  
4              NaN

In [5]:
store.describe()

Store  CompetitionDistance  CompetitionOpenSinceMonth  \
count  1115.00000          1112.000000                 761.000000   
mean    558.00000          5404.901079                   7.224704   
std     322.01708          7663.174720                   3.212348   
min       1.00000            20.000000                   1.000000   
25%     279.50000           717.500000                   4.000000   
50%     558.00000          2325.000000                   8.000000   
75%     836.50000          6882.500000                  10.000000   
max    1115.00000         75860.000000                  12.000000   

       CompetitionOpenSinceYear       Promo2  Promo2SinceWeek  Promo2SinceYear  
count                761.000000  1115.000000       571.000000       571.000000  
mean                2008.668857     0.512108        23.595447      2011.763573  
std                    6.195983     0.500078        14.141984         1.674935  
min                 1900.000000     0.000000         1.000000      2009.000000  
25%                 2006.000000     0.000000        13.000000      2011.000000  
50%                 2010.000000     1.000000        22.000000      2012.000000  
75%                 2013.000000     1.000000        37.000000      2013.000000  
max                 2015.000000     1.000000        50.000000      2015.000000

In [6]:
store.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1115 entries, 0 to 1114
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Store                      1115 non-null   int64  
 1   StoreType                  1115 non-null   object 
 2   Assortment                 1115 non-null   object 
 3   CompetitionDistance        1112 non-null   float64
 4   CompetitionOpenSinceMonth  761 non-null    float64
 5   CompetitionOpenSinceYear   761 non-null    float64
 6   Promo2                     1115 non-null   int64  
 7   Promo2SinceWeek            571 non-null    float64
 8   Promo2SinceYear            571 non-null    float64
 9   PromoInterval              571 non-null    object 
dtypes: float64(5), int64(2), object(3)
memory usage: 87.2+ KB


In [7]:
store.isnull().sum()

Store                          0
StoreType                      0
Assortment                     0
CompetitionDistance            3
CompetitionOpenSinceMonth    354
CompetitionOpenSinceYear     354
Promo2                         0
Promo2SinceWeek              544
Promo2SinceYear              544
PromoInterval                544
dtype: int64

In [8]:
unique_vals(store)

Store
[ 1  2  3  4  5  6  7  8  9 10]
__________________
******************

StoreType
['c' 'a' 'd' 'b']
__________________
******************

Assortment
['a' 'c' 'b']
__________________
******************

CompetitionDistance
[ 1270.   570. 14130.   620. 29910.   310. 24000.  7520.  2030.  3160.]
__________________
******************

CompetitionOpenSinceMonth
[ 9. 11. 12.  4. 10.  8. nan  3.  6.  5.]
__________________
******************

CompetitionOpenSinceYear
[2008. 2007. 2006. 2009. 2015. 2013. 2014. 2000. 2011.   nan]
__________________
******************

Promo2
[0 1]
__________________
******************

Promo2SinceWeek
[nan 13. 14.  1. 45. 40. 26. 22.  5.  6.]
__________________
******************

Promo2SinceYear
[  nan 2010. 2011. 2012. 2009. 2014. 2015. 2013.]
__________________
******************

PromoInterval
[nan 'Jan,Apr,Jul,Oct' 'Feb,May,Aug,Nov' 'Mar,Jun,Sept,Dec']
__________________
******************



### train sales dataset

In [9]:
train.isnull().sum()

Store            0
DayOfWeek        0
Date             0
Sales            0
Customers        0
Open             0
Promo            0
StateHoliday     0
SchoolHoliday    0
dtype: int64

In [10]:
unique_vals(train)

Store
[ 1  2  3  4  5  6  7  8  9 10]
__________________
******************

DayOfWeek
[5 4 3 2 1 7 6]
__________________
******************

Date
['2015-07-31' '2015-07-30' '2015-07-29' '2015-07-28' '2015-07-27'
 '2015-07-26' '2015-07-25' '2015-07-24' '2015-07-23' '2015-07-22']
__________________
******************

Sales
[ 5263  6064  8314 13995  4822  5651 15344  8492  8565  7185]
__________________
******************

Customers
[ 555  625  821 1498  559  589 1414  833  687  681]
__________________
******************

Open
[1 0]
__________________
******************

Promo
[1 0]
__________________
******************

StateHoliday
['0' 'a' 'b' 'c' 0]
__________________
******************

SchoolHoliday
[1 0]
__________________
******************



In [11]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1017209 entries, 0 to 1017208
Data columns (total 9 columns):
 #   Column         Non-Null Count    Dtype 
---  ------         --------------    ----- 
 0   Store          1017209 non-null  int64 
 1   DayOfWeek      1017209 non-null  int64 
 2   Date           1017209 non-null  object
 3   Sales          1017209 non-null  int64 
 4   Customers      1017209 non-null  int64 
 5   Open           1017209 non-null  int64 
 6   Promo          1017209 non-null  int64 
 7   StateHoliday   1017209 non-null  object
 8   SchoolHoliday  1017209 non-null  int64 
dtypes: int64(7), object(2)
memory usage: 69.8+ MB


In [12]:
train.describe()

Store     DayOfWeek         Sales     Customers          Open  \
count  1.017209e+06  1.017209e+06  1.017209e+06  1.017209e+06  1.017209e+06   
mean   5.584297e+02  3.998341e+00  5.773819e+03  6.331459e+02  8.301067e-01   
std    3.219087e+02  1.997391e+00  3.849926e+03  4.644117e+02  3.755392e-01   
min    1.000000e+00  1.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
25%    2.800000e+02  2.000000e+00  3.727000e+03  4.050000e+02  1.000000e+00   
50%    5.580000e+02  4.000000e+00  5.744000e+03  6.090000e+02  1.000000e+00   
75%    8.380000e+02  6.000000e+00  7.856000e+03  8.370000e+02  1.000000e+00   
max    1.115000e+03  7.000000e+00  4.155100e+04  7.388000e+03  1.000000e+00   

              Promo  SchoolHoliday  
count  1.017209e+06   1.017209e+06  
mean   3.815145e-01   1.786467e-01  
std    4.857586e-01   3.830564e-01  
min    0.000000e+00   0.000000e+00  
25%    0.000000e+00   0.000000e+00  
50%    0.000000e+00   0.000000e+00  
75%    1.000000e+00   0.000000e+00  
max    1.000000e+00   1.000000e+00

## Missing Value Treatment
* Promo2 Identifies if the store participates in the consecutive promotion. so Promo2=0 indicates the store didn't participate. 
* so the values Promo2Since[Year/Month] will be zero.

In [13]:
(train.Store.unique()== store.Store.unique()).sum(), store.Store.nunique()

(1115, 1115)

In [14]:
store

Store StoreType Assortment  CompetitionDistance  \
0         1         c          a               1270.0   
1         2         a          a                570.0   
2         3         a          a              14130.0   
3         4         c          c                620.0   
4         5         a          a              29910.0   
...     ...       ...        ...                  ...   
1110   1111         a          a               1900.0   
1111   1112         c          c               1880.0   
1112   1113         a          c               9260.0   
1113   1114         a          c                870.0   
1114   1115         d          c               5350.0   

      CompetitionOpenSinceMonth  CompetitionOpenSinceYear  Promo2  \
0                           9.0                    2008.0       0   
1                          11.0                    2007.0       1   
2                          12.0                    2006.0       1   
3                           9.0                    2009.0       0   
4                           4.0                    2015.0       0   
...                         ...                       ...     ...   
1110                        6.0                    2014.0       1   
1111                        4.0                    2006.0       0   
1112                        NaN                       NaN       0   
1113                        NaN                       NaN       0   
1114                        NaN                       NaN       1   

      Promo2SinceWeek  Promo2SinceYear     PromoInterval  
0                 NaN              NaN               NaN  
1                13.0           2010.0   Jan,Apr,Jul,Oct  
2                14.0           2011.0   Jan,Apr,Jul,Oct  
3                 NaN              NaN               NaN  
4                 NaN              NaN               NaN  
...               ...              ...               ...  
1110             31.0           2013.0   Jan,Apr,Jul,Oct  
1111              NaN              NaN               NaN  
1112              NaN              NaN               NaN  
1113              NaN              NaN               NaN  
1114             22.0           2012.0  Mar,Jun,Sept,Dec  

[1115 rows x 10 columns]

In [15]:
store.isnull().sum()/store.shape[0]*100

Store                         0.000000
StoreType                     0.000000
Assortment                    0.000000
CompetitionDistance           0.269058
CompetitionOpenSinceMonth    31.748879
CompetitionOpenSinceYear     31.748879
Promo2                        0.000000
Promo2SinceWeek              48.789238
Promo2SinceYear              48.789238
PromoInterval                48.789238
dtype: float64

In [16]:
store.Promo2.value_counts()

1    571
0    544
Name: Promo2, dtype: int64

In [17]:
store[store.Promo2 ==0].isnull().sum()/store.shape[0]*100

Store                         0.000000
StoreType                     0.000000
Assortment                    0.000000
CompetitionDistance           0.179372
CompetitionOpenSinceMonth    13.273543
CompetitionOpenSinceYear     13.273543
Promo2                        0.000000
Promo2SinceWeek              48.789238
Promo2SinceYear              48.789238
PromoInterval                48.789238
dtype: float64

In [18]:
# both Promo2since_* are null when Promo2==0, since they can't exist for such senario
store[store.Promo2 ==0].Promo2SinceWeek.isnull().sum(), store[store.Promo2 ==0].Promo2SinceYear.isnull().sum()

(544, 544)

In [19]:
store.loc[store['Promo2']==0,['Promo2SinceWeek','Promo2SinceYear']] = 0

In [20]:
store.PromoInterval.unique()

array([nan, 'Jan,Apr,Jul,Oct', 'Feb,May,Aug,Nov', 'Mar,Jun,Sept,Dec'],
      dtype=object)

In [21]:
store.loc[store['Promo2']==0,['PromoInterval']] = '0,0,0,0'

In [22]:
store.isnull().sum()

Store                          0
StoreType                      0
Assortment                     0
CompetitionDistance            3
CompetitionOpenSinceMonth    354
CompetitionOpenSinceYear     354
Promo2                         0
Promo2SinceWeek                0
Promo2SinceYear                0
PromoInterval                  0
dtype: int64

In [23]:
store[store.CompetitionOpenSinceYear.isnull() & store.CompetitionOpenSinceMonth.isnull()].shape

(354, 10)

In [24]:
store.loc[store.CompetitionOpenSinceYear.isnull(),['CompetitionOpenSinceYear']] = store.CompetitionOpenSinceYear.min()
store.loc[store.CompetitionOpenSinceMonth.isnull(),['CompetitionOpenSinceMonth']] = store.CompetitionOpenSinceMonth.min()

In [25]:
store.loc[store['CompetitionDistance'].isnull(),'CompetitionDistance'] = store.CompetitionDistance.mean()

In [26]:
store.isnull().sum().sum()

0

## Dataset Merging
* train and test datasets will be merged with store information

In [27]:
store.columns, train.columns

(Index(['Store', 'StoreType', 'Assortment', 'CompetitionDistance',
        'CompetitionOpenSinceMonth', 'CompetitionOpenSinceYear', 'Promo2',
        'Promo2SinceWeek', 'Promo2SinceYear', 'PromoInterval'],
       dtype='object'),
 Index(['Store', 'DayOfWeek', 'Date', 'Sales', 'Customers', 'Open', 'Promo',
        'StateHoliday', 'SchoolHoliday'],
       dtype='object'))

In [28]:
train.head()

Store  DayOfWeek        Date  Sales  Customers  Open  Promo StateHoliday  \
0      1          5  2015-07-31   5263        555     1      1            0   
1      2          5  2015-07-31   6064        625     1      1            0   
2      3          5  2015-07-31   8314        821     1      1            0   
3      4          5  2015-07-31  13995       1498     1      1            0   
4      5          5  2015-07-31   4822        559     1      1            0   

   SchoolHoliday  
0              1  
1              1  
2              1  
3              1  
4              1

In [29]:
train.insert(0,'Id',train.index,True)

In [34]:
df_train = train.merge(store,on='Store',how='inner')
df_test = test.merge(store,on='Store',how='inner')

In [31]:
df_train.head()

Id  Store  DayOfWeek        Date  Sales  Customers  Open  Promo  \
0     0      1          5  2015-07-31   5263        555     1      1   
1  1115      1          4  2015-07-30   5020        546     1      1   
2  2230      1          3  2015-07-29   4782        523     1      1   
3  3345      1          2  2015-07-28   5011        560     1      1   
4  4460      1          1  2015-07-27   6102        612     1      1   

  StateHoliday  SchoolHoliday StoreType Assortment  CompetitionDistance  \
0            0              1         c          a               1270.0   
1            0              1         c          a               1270.0   
2            0              1         c          a               1270.0   
3            0              1         c          a               1270.0   
4            0              1         c          a               1270.0   

   CompetitionOpenSinceMonth  CompetitionOpenSinceYear  Promo2  \
0                        9.0                    2008.0       0   
1                        9.0                    2008.0       0   
2                        9.0                    2008.0       0   
3                        9.0                    2008.0       0   
4                        9.0                    2008.0       0   

   Promo2SinceWeek  Promo2SinceYear PromoInterval  
0              0.0              0.0       0,0,0,0  
1              0.0              0.0       0,0,0,0  
2              0.0              0.0       0,0,0,0  
3              0.0              0.0       0,0,0,0  
4              0.0              0.0       0,0,0,0

In [35]:
df_train.shape, df_train.Id.nunique()

((1017209, 19), 1017209)

## Save dataset
- saves the finalized dataset

In [38]:
df_train.to_csv('../data/df_train.csv',index=False)
df_test.to_csv('../data/df_test.csv',index=False)